//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualDevice.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VirtualDevice.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краткое название прибора:SHOCK___
        ///Модификация:??
        ///Версия ПО или пакета данных:01
        ///Дата составления файла:DD
        ///Месяц составления файла:MM
        ///Год составления файла:YY
        ///Указатель типа файла:K_
        ///Серийный номер прибора:65535
        ///Резерв:00 00 00 00 00 00 00 00 00 00 00 00 00 00
        ///Калибровки[]:Name=&quot;G0_&quot; ItemType=0 DataType=8 Data=517 517 517
        ///Калибровки[]:Name=&quot;POR_&quot; ItemType=0 DataType=8 Data=41 82 164 246
        ///Калибровки[]:Name=&quot;TMR&quot; ItemType=0 DataType=8 Data=2.
        /// </summary>
        internal static string ID5_V01_CALIBRATION {
            get {
                return ResourceManager.GetString("ID5_V01_CALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краткое название прибора:INCL____
        ///Модификация:??
        ///Версия ПО или пакета данных:01
        ///Дата составления файла:DD
        ///Месяц составления файла:MM
        ///Год составления файла:YY
        ///Указатель типа файла:K_
        ///Серийный номер прибора:999
        ///Резерв:00 00 00 00 00 00 00 00 00 00 00 00 00 00
        ///Калибровки:.
        /// </summary>
        internal static string V01_RUS03_Cal {
            get {
                return ResourceManager.GetString("V01_RUS03_Cal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краткое название прибора:INCL____
        ///Модификация:??
        ///Версия ПО или пакета данных:01
        ///Дата составления файла:DD
        ///Месяц составления файла:MM
        ///Год составления файла:YY
        ///Указатель типа файла:S_
        ///Серийный номер прибора:999
        ///Резерв:00 00 00 00 00 00 00 00 00 00 00 00 00 00
        ///Текстовый файл:??.
        /// </summary>
        internal static string V01_RUS03_FSet {
            get {
                return ResourceManager.GetString("V01_RUS03_FSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краткое название прибора:INCL____
        ///Модификация:??
        ///Версия ПО или пакета данных:01
        ///Дата составления файла:DD
        ///Месяц составления файла:MM
        ///Год составления файла:YY
        ///Указатель типа файла:T_
        ///Серийный номер прибора:999
        ///Резерв:00 00 00 00 00 00 00 00 00 00 00 00 00 00
        ///Калибровки:.
        /// </summary>
        internal static string V01_RUS03_TCal {
            get {
                return ResourceManager.GetString("V01_RUS03_TCal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краткое название прибора:SHOCK___
        ///Модификация:??
        ///Версия ПО или пакета данных:01
        ///Дата составления файла:DD
        ///Месяц составления файла:MM
        ///Год составления файла:YY
        ///Указатель типа файла:K_
        ///Серийный номер прибора:65535
        ///Резерв:00 00 00 00 00 00 00 00 00 00 00 00 00 00
        ///Калибровки[]:Name=&quot;G0_&quot; ItemType=0 DataType=8 Data=517 517 517
        ///Калибровки[]:Name=&quot;POR_&quot; ItemType=0 DataType=8 Data=41 82 164 246
        ///Калибровки[]:Name=&quot;TMR&quot; ItemType=0 DataType=8 Data=2.
        /// </summary>
        internal static string V01_RUS05_Cal {
            get {
                return ResourceManager.GetString("V01_RUS05_Cal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краткое название прибора:SHOCK___
        ///Модификация:??
        ///Версия ПО или пакета данных:01
        ///Дата составления файла:DD
        ///Месяц составления файла:MM
        ///Год составления файла:YY
        ///Указатель типа файла:F_
        ///Серийный номер прибора:65535
        ///Резерв:00 00 00 00 00 00 00 00 00 00 00 00 00 00
        ///Массив описаний пакета данных[]:Name=&quot;SH5O&quot; Position=1 Length=2 NumOfSignificantBits=16 IsSigned=False 
        ///Массив описаний пакета данных[]:Name=&quot;SH1O&quot; Position=3 Length=2 NumOfSignificantBits=16 IsSigned=False 
        ///Массив описаний пакета данных[]:N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string V01_RUS05_DPConf {
            get {
                return ResourceManager.GetString("V01_RUS05_DPConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краткое название прибора:SHOCK___
        ///Модификация:??
        ///Версия ПО или пакета данных:01
        ///Дата составления файла:DD
        ///Месяц составления файла:MM
        ///Год составления файла:YY
        ///Указатель типа файла:S_
        ///Серийный номер прибора:65535
        ///Резерв:00 00 00 00 00 00 00 00 00 00 00 00 00 00
        ///Текстовый файл:??.
        /// </summary>
        internal static string V01_RUS05_FSet {
            get {
                return ResourceManager.GetString("V01_RUS05_FSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краткое название прибора:Bl_Gyro_
        ///Модификация:??
        ///Версия ПО или пакета данных:01
        ///Дата составления файла:DD
        ///Месяц составления файла:MM
        ///Год составления файла:YY
        ///Указатель типа файла:K_
        ///Серийный номер прибора:65535
        ///Резерв:00 00 00 00 00 00 00 00 00 00 00 00 00 00
        ///Калибровки:.
        /// </summary>
        internal static string V01_RUS07_Cal {
            get {
                return ResourceManager.GetString("V01_RUS07_Cal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краткое название прибора:Bl_Gyro_
        ///Модификация:??
        ///Версия ПО или пакета данных:01
        ///Дата составления файла:DD
        ///Месяц составления файла:MM
        ///Год составления файла:YY
        ///Указатель типа файла:S_
        ///Серийный номер прибора:65535
        ///Резерв:00 00 00 00 00 00 00 00 00 00 00 00 00 00
        ///Текстовый файл:??.
        /// </summary>
        internal static string V01_RUS07_FSet {
            get {
                return ResourceManager.GetString("V01_RUS07_FSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краткое название прибора:Bl_Gyro_
        ///Модификация:??
        ///Версия ПО или пакета данных:01
        ///Дата составления файла:DD
        ///Месяц составления файла:MM
        ///Год составления файла:YY
        ///Указатель типа файла:T_
        ///Серийный номер прибора:65535
        ///Резерв:00 00 00 00 00 00 00 00 00 00 00 00 00 00
        ///Калибровки[]:Name=&quot;AH1&quot; ItemType=8 DataType=8 Data=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string V01_RUS07_TCal {
            get {
                return ResourceManager.GetString("V01_RUS07_TCal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краткое название прибора:SNAPUNIT
        ///Модификация:??
        ///Версия ПО или пакета данных:01
        ///Дата составления файла:DD
        ///Месяц составления файла:MM
        ///Год составления файла:YY
        ///Указатель типа файла:K_
        ///Серийный номер прибора:65535
        ///Резерв:00 00 00 00 00 00 00 00 00 00 00 00 00 00
        ///Калибровки:.
        /// </summary>
        internal static string V01_RUS09_Cal {
            get {
                return ResourceManager.GetString("V01_RUS09_Cal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краткое название прибора:SNAPUNIT
        ///Модификация:??
        ///Версия ПО или пакета данных:01
        ///Дата составления файла:DD
        ///Месяц составления файла:MM
        ///Год составления файла:YY
        ///Указатель типа файла:F_
        ///Серийный номер прибора:65535
        ///Резерв:00 00 00 00 00 00 00 00 00 00 00 00 00 00
        ///Массив описаний пакета данных:.
        /// </summary>
        internal static string V01_RUS09_DPConf {
            get {
                return ResourceManager.GetString("V01_RUS09_DPConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краткое название прибора:SNAPUNIT
        ///Модификация:??
        ///Версия ПО или пакета данных:01
        ///Дата составления файла:DD
        ///Месяц составления файла:MM
        ///Год составления файла:YY
        ///Указатель типа файла:S_
        ///Серийный номер прибора:65535
        ///Резерв:00 00 00 00 00 00 00 00 00 00 00 00 00 00
        ///Текстовый файл:??.
        /// </summary>
        internal static string V01_RUS09_FSet {
            get {
                return ResourceManager.GetString("V01_RUS09_FSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краткое название прибора:TexModul
        ///Модификация:TS
        ///Версия ПО или пакета данных:01
        ///Дата составления файла:05
        ///Месяц составления файла:11
        ///Год составления файла:19
        ///Указатель типа файла:K_
        ///Серийный номер прибора:100
        ///Резерв:CA F0 00 00 00 00 00 00 00 00 00 00 00 FF
        ///Калибровки:11 22 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 FF.
        /// </summary>
        internal static string V01_RUS24_Cal {
            get {
                return ResourceManager.GetString("V01_RUS24_Cal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краткое название прибора:TexModul
        ///Модификация:TS
        ///Версия ПО или пакета данных:01
        ///Дата составления файла:05
        ///Месяц составления файла:11
        ///Год составления файла:19
        ///Указатель типа файла:F_
        ///Серийный номер прибора:100
        ///Резерв:00 00 00 00 00 00 00 00 00 00 00 00 00 FF
        ///Массив описаний пакета данных:.
        /// </summary>
        internal static string V01_RUS24_DPConf {
            get {
                return ResourceManager.GetString("V01_RUS24_DPConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краткое название прибора:TexModul
        ///Модификация:TS
        ///Версия ПО или пакета данных:01
        ///Дата составления файла:05
        ///Месяц составления файла:11
        ///Год составления файла:19
        ///Указатель типа файла:S_
        ///Серийный номер прибора:100
        ///Резерв:FC E0 00 00 00 00 00 00 00 00 00 00 00 FF
        ///Массив UInt8[36]:00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 FF.
        /// </summary>
        internal static string V01_RUS24_FSet {
            get {
                return ResourceManager.GetString("V01_RUS24_FSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краткое название прибора:TexModul
        ///Модификация:TS
        ///Версия ПО или пакета данных:01
        ///Дата составления файла:05
        ///Месяц составления файла:11
        ///Год составления файла:19
        ///Указатель типа файла:T_
        ///Серийный номер прибора:100
        ///Резерв:CA F0 00 00 00 00 00 00 00 00 00 00 00 FF
        ///Калибровки:00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 FF.
        /// </summary>
        internal static string V01_RUS24_TCal {
            get {
                return ResourceManager.GetString("V01_RUS24_TCal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краткое название прибора:TexModul
        ///Модификация:TS
        ///Версия ПО или пакета данных:01
        ///Дата составления файла:05
        ///Месяц составления файла:11
        ///Год составления файла:19
        ///Указатель типа файла:R_
        ///Серийный номер прибора:100
        ///Резерв:F0 00 00 00 00 00 00 00 00 00 00 00 00 FF
        ///Режим работы:00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 FF.
        /// </summary>
        internal static string V01_RUS24_WMode {
            get {
                return ResourceManager.GetString("V01_RUS24_WMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краткое название прибора:EMC_Mdl_
        ///Модификация:??
        ///Версия ПО или пакета данных:01
        ///Дата составления файла:DD
        ///Месяц составления файла:MM
        ///Год составления файла:YY
        ///Указатель типа файла:K_
        ///Серийный номер прибора:100
        ///Резерв:00 00 00 00 00 00 00 00 00 00 00 00 00 00
        ///Калибровки:.
        /// </summary>
        internal static string V01_RUS40_Cal {
            get {
                return ResourceManager.GetString("V01_RUS40_Cal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краткое название прибора:EMC_Mdl_
        ///Модификация:??
        ///Версия ПО или пакета данных:01
        ///Дата составления файла:DD
        ///Месяц составления файла:MM
        ///Год составления файла:YY
        ///Указатель типа файла:S_
        ///Серийный номер прибора:100
        ///Резерв:00 00 00 00 00 00 00 00 00 00 00 00 00 00
        ///Текстовый файл:??.
        /// </summary>
        internal static string V01_RUS40_FSet {
            get {
                return ResourceManager.GetString("V01_RUS40_FSet", resourceCulture);
            }
        }
    }
}
