//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceBaseTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeviceBaseTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краткое название прибора:INCL____
        ///Модификация:??
        ///Версия ПО или пакета данных:01
        ///Дата составления файла:28
        ///Месяц составления файла:07
        ///Год составления файла:19
        ///Указатель типа файла:T_
        ///Серийный номер прибора:65535
        ///Резерв:00 00 00 00 00 00 00 00 00 00 00 00 00 00
        ///Калибровки:.
        /// </summary>
        internal static string EmptyInclinometrTCal_V7_0_0 {
            get {
                return ResourceManager.GetString("EmptyInclinometrTCal_V7_0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000:Краткое название прибора:INCL____
        ///008:Модификация:??
        ///010:Версия ПО или пакета данных:01
        ///012:Дата составления файла:25
        ///014:Месяц составления файла:07
        ///016:Год составления файла:19
        ///018:Указатель типа файла:T_
        ///020:Серийный номер прибора:65535
        ///022:Резерв:00 00 00 00 00 00 00 00 00 00 00 00 00 00
        ///036:Калибровки:47 31 78 00 05 0D 04 60 3F 8F 0B 07 3E B0 CB 08 3F 8C E0 01 3E B5 99 89 3F 8A 6F 3F 3E BA 7C 18 3F 87 B2 0C 3E BF 6C 6A 3F 84 A1 BE 3E C4 63 28 3F 81 37 B9 3E C9 57 47 3F 7A DB A5 3E CE 3E D1  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InclinometrTCal_V6_0_0 {
            get {
                return ResourceManager.GetString("InclinometrTCal_V6_0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краткое название прибора:INCL____
        ///Модификация:??
        ///Версия ПО или пакета данных:01
        ///Дата составления файла:28
        ///Месяц составления файла:07
        ///Год составления файла:19
        ///Указатель типа файла:T_
        ///Серийный номер прибора:65535
        ///Резерв:00 00 00 00 00 00 00 00 00 00 00 00 00 00
        ///Калибровки[]:Name=&quot;G1x&quot; ItemType=5 DataType=13 Data=-0.002202 1.001747 -0.002119 1.001679 -0.002034 1.001611 -0.00195 1.001543 -0.001866 1.001474 -0.001782 1.001406 -0.001697 1.001337 -0.001613 1.001269 -0.001528 1.0012 -0.001444 1.001132 -0.0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InclinometrTCal_V7_0_0 {
            get {
                return ResourceManager.GetString("InclinometrTCal_V7_0_0", resourceCulture);
            }
        }
    }
}
