//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UpdateManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RSAKeyValue&gt;&lt;Modulus&gt;5WXYeqC78zOptbk92wTrJxEjU/JXviNaSNaD/ss1OO7VHH2He2WXs9HHUntUoLeBodqurSbU447P3ii6e8vG7v6dp6zIImcq1v9kyFl1HYQALGSSJO3mCgHEi5QK+av5g0Kn3HvReWIbtng4Uuzs9zCFhJ35duE48carawYeE+KOD1tX0kF4/ZuewKkdW1MAl2/lvPcwC+Qu8rUle5/4FAdT/Su/IzBXceEdmoFz8UE1PfHFAY2+JpXjr8L2UpQnivDKPUmf6rDr7th8gVAFXtNRV6ZNoBgfV9vC624OMb07nm0mgXcxADA15nzziXkvvD5PYli/kBg13+lfUtMrMtTLa0yASpGc6j1+pjPobR1ND7Uid8uurBgRx6qYNlpKldzi7tDtQhiPWULGCf4m2mIwZwzjpPjS3pJps/rDKftmGpNzbOoK+jDOjdXeQQMT1HqXg/ZNtPOr0bn4kIE9tQtJZJK4JYPj/C4EErU031 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PublicRSA4096Key {
            get {
                return ResourceManager.GetString("PublicRSA4096Key", resourceCulture);
            }
        }
    }
}
